trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: 'src/apsys.ndbunit.netcore.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
