trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: 'src/apsys.ndbunit.netcore.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: ''

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/apsys.ndbunit.netcore/apsys.ndbunit.netcore.csproj'
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'apsys nuget server'