trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: 'src/apsys.ndbunit.netcore.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: ''

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: 'src/apsys.ndbunit.netcore'
    nobuild: true
    versioningScheme: 'off'
