trigger:
- devel

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: 'src/apsys.ndbunit.netcore.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: ''
  buildN: '3'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'